In [3]:
import pandas as pd
df = pd.read_csv(r"D:\Codes\MachineLearning\Datasets\purchase.csv")
df 

Person  Ball  Bat  apple  Orange  Price
0      A   3.0  2.0   20.0    20.0    NaN
1      B   2.0  NaN   30.0    40.0    NaN
2      C   NaN  3.0   50.0    70.0  123.0
3      D   4.0  3.0   10.0   100.0    NaN
4      E   NaN  6.0   80.0   150.0    NaN
5      F   2.0  NaN   90.0     NaN  456.0
6      G   2.0  7.0  100.0     NaN  890.0
7      H   NaN  2.0   70.0     NaN  145.0
8      I   6.0  NaN    NaN     NaN  776.0
9      J   1.0  NaN    NaN     NaN  998.0

In [4]:
df["Ball"] = df["Ball"].fillna(df["Ball"].median())
df

Person  Ball  Bat  apple  Orange  Price
0      A   3.0  2.0   20.0    20.0    NaN
1      B   2.0  NaN   30.0    40.0    NaN
2      C   2.0  3.0   50.0    70.0  123.0
3      D   4.0  3.0   10.0   100.0    NaN
4      E   2.0  6.0   80.0   150.0    NaN
5      F   2.0  NaN   90.0     NaN  456.0
6      G   2.0  7.0  100.0     NaN  890.0
7      H   2.0  2.0   70.0     NaN  145.0
8      I   6.0  NaN    NaN     NaN  776.0
9      J   1.0  NaN    NaN     NaN  998.0

In [5]:
df.describe()

Ball       Bat       apple      Orange       Price
count  10.000000  6.000000    8.000000    5.000000    6.000000
mean    2.600000  3.833333   56.250000   76.000000  564.666667
std     1.429841  2.136976   33.779749   51.283526  379.810304
min     1.000000  2.000000   10.000000   20.000000  123.000000
25%     2.000000  2.250000   27.500000   40.000000  222.750000
50%     2.000000  3.000000   60.000000   70.000000  616.000000
75%     2.750000  5.250000   82.500000  100.000000  861.500000
max     6.000000  7.000000  100.000000  150.000000  998.000000

In [6]:
df["Bat"] = df["Bat"].fillna(df["Bat"].mean())
df

Person  Ball       Bat  apple  Orange  Price
0      A   3.0  2.000000   20.0    20.0    NaN
1      B   2.0  3.833333   30.0    40.0    NaN
2      C   2.0  3.000000   50.0    70.0  123.0
3      D   4.0  3.000000   10.0   100.0    NaN
4      E   2.0  6.000000   80.0   150.0    NaN
5      F   2.0  3.833333   90.0     NaN  456.0
6      G   2.0  7.000000  100.0     NaN  890.0
7      H   2.0  2.000000   70.0     NaN  145.0
8      I   6.0  3.833333    NaN     NaN  776.0
9      J   1.0  3.833333    NaN     NaN  998.0

In [ ]:
# print(df["apple"].median())
# print(df["Bat"].mode())

df["apple"] = df["apple"].fillna(df["apple"].mean())
df["Orange"] = df["Orange"].fillna(df["Orange"].mean())
df["Price"] = df["Price"].fillna(df["Price"].median())
df


Person  Ball       Bat   apple  Orange  Price
0      A   3.0  2.000000   20.00    20.0  616.0
1      B   2.0  3.833333   30.00    40.0  616.0
2      C   2.0  3.000000   50.00    70.0  123.0
3      D   4.0  3.000000   10.00   100.0  616.0
4      E   2.0  6.000000   80.00   150.0  616.0
5      F   2.0  3.833333   90.00    76.0  456.0
6      G   2.0  7.000000  100.00    76.0  890.0
7      H   2.0  2.000000   70.00    76.0  145.0
8      I   6.0  3.833333   56.25    76.0  776.0
9      J   1.0  3.833333   56.25    76.0  998.0

In [ ]:
from pandas import read_csv
from numpy import set_printoptions
from sklearn import preprocessing
name = ["A","B","C","D","E","F","G","H","I"]
df = read_csv(r"D:\Codes\MachineLearning\Datasets\pima-inians-diabetes.csv", names=name, header=0)

df.describe()

A           B           C           D           E           F  \
count  767.000000  767.000000  767.000000  767.000000  767.000000  767.000000   
mean     3.842243  120.859192   69.101695   20.517601   79.903520   31.990482   
std      3.370877   31.978468   19.368155   15.954059  115.283105    7.889091   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   32.000000   32.000000   
75%      6.000000  140.000000   80.000000   32.000000  127.500000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

                G           H           I  
count  767.000000  767.000000  767.000000  
mean     0.471674   33.219035    0.348110  
std      0.331497   11.752296    0.476682  
min      0.078000   21.000000    0.000000  
25%      0.243500   24.000000    0.000000  
50%      0.371000   29.000000    0.000000  
75%      0.625000   41.000000    1.000000  
max      2.420000   81.000000    1.000000

In [22]:
scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
rescaled = scaler.fit_transform(df)
set_printoptions(precision=2)
rescaled


array([[0.06, 0.43, 0.54, ..., 0.12, 0.17, 0.  ],
       [0.47, 0.92, 0.52, ..., 0.25, 0.18, 1.  ],
       [0.06, 0.45, 0.54, ..., 0.04, 0.  , 0.  ],
       ...,
       [0.29, 0.61, 0.59, ..., 0.07, 0.15, 0.  ],
       [0.06, 0.63, 0.49, ..., 0.12, 0.43, 1.  ],
       [0.06, 0.47, 0.57, ..., 0.1 , 0.03, 0.  ]], shape=(767, 9))

In [25]:
from sklearn.preprocessing import StandardScaler
data_scaler = StandardScaler().fit(df)
data_rescaled = data_scaler.transform(df)
data_rescaled

array([[-0.84, -1.12, -0.16, ..., -0.36, -0.19, -0.73],
       [ 1.23,  1.94, -0.26, ...,  0.6 , -0.1 ,  1.37],
       [-0.84, -1.  , -0.16, ..., -0.92, -1.04, -0.73],
       ...,
       [ 0.34,  0.  ,  0.15, ..., -0.68, -0.27, -0.73],
       [-0.84,  0.16, -0.47, ..., -0.37,  1.17,  1.37],
       [-0.84, -0.87,  0.05, ..., -0.47, -0.87, -0.73]], shape=(767, 9))

In [26]:
from sklearn.preprocessing import Binarizer
binary = Binarizer(threshold=0.5)
binary1 = binary.transform(df)
binary1

c:\Users\NoNeo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but Binarizer was fitted without feature names
  warnings.warn(


array([[1., 1., 1., ..., 0., 1., 0.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 0., 1., 0.],
       ...,
       [1., 1., 1., ..., 0., 1., 0.],
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 0., 1., 0.]], shape=(767, 9))